# Copyright 2025 Richard Kosegi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
version: 2
project_name: yaml-pipeline
changelog:
  use: github-native
release:
  github: {}
before:
  hooks:
    - go mod tidy
builds:
  - id: yp
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64_v1
      - linux_arm64
      - darwin_amd64_v1
      - darwin_arm64
      - windows_amd64_v1
      - windows_arm64
    dir: pkg/cmd/cli
    main: main.go
    binary: yp
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/rkosegi/yaml-pipeline/pkg/version.BuildDate={{ .Date }}
      - -X github.com/rkosegi/yaml-pipeline/pkg/version.Version={{ .Version }}
      - -X github.com/rkosegi/yaml-pipeline/pkg/version.Revision={{ .ShortCommit }}
      - -X github.com/rkosegi/yaml-pipeline/pkg/version.Branch={{ .Branch }}
      - -X github.com/rkosegi/yaml-pipeline/pkg/version.Tag={{ .Tag }}
